validate-all: More logging

diff --git a/validate-all b/validate-all
--- a/validate-all
+++ b/validate-all
@@ -24,22 +24,33 @@ function try() {
     $@
     ret=$?
     if [ $ret != 0 ]; then
-        echo "Failed to $label" | tee -a $log
+        echo "Failed to $label ($ret)" | tee -a $log
     fi
     return $ret
 }
 
+function validate() {
+    commit=$1
+    echo -e "\nTesting $commit" | tee -a $log
+
+    try "checkout" checkout $(echo "$commits" | head -n1) || exit 1
+    if [ "x$force_clean" == "x1" ]; then
+        try "validate" ./validate
+    else
+        if try "validate" ./validate --no-clean; then
+            try "clean validate" ./validate || return $?
+        fi
+    fi
+}
+
 # Start with clean validation
-try "checkout" checkout $(echo "$commits" | head -n1) || exit 1
-if [ ! -z "$no_clean" ]; then no_clean="--no-clean"; fi
-try "validate" ./validate $no_clean
+if [ "x$no_clean" != "x1" ]; then force_clean=1; fi
+commit=$(echo "$commits" | head -n1)
+validate $commit $no_clean | tee validate-$commit.log
+force_clean=0
 
 for commit in $(echo "$commits" | tail -n1); do
-    echo -e "\nTesting $commit" | tee -a $log
-    try "checkout" checkout $commit || continue
-    if try "validate" ./validate --no-clean; then
-        try "clean validate" ./validate || continue
-    fi
+    validate $commit | tee validate-$commit.log
 done
 
 echo "Finished $(date)" | tee -a $log
